manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: corne-wireless-5-col-zmk-config
      url-base: https://github.com/jwrunge
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: corne-wireless-5-col-zmk-config
      remote: jwrunge
      revision: main
  self:
    path: config
